---
- name: Get System Specifications for All Hosts
  hosts: all
  gather_facts: yes

  tasks:
    - name: Display CPU Usage
      ansible.builtin.shell:
        cmd: |
          {% if 'linux' in ansible_os_family|lower %}
          top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'
          {% elif 'win' in ansible_os_family|lower %}
          Get-Counter '\Processor(_Total)\% Processor Time' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue
          {% else %}
          echo "Unsupported OS"
          {% endif %}
      register: cpu_output

    - name: Display Memory Information
      ansible.builtin.shell:
        cmd: |
          {% if 'linux' in ansible_os_family|lower %}
          free -m
          {% elif 'win' in ansible_os_family|lower %}
          Get-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize, FreePhysicalMemory | ConvertTo-Json
          {% else %}
          echo "Unsupported OS"
          {% endif %}
      register: memory_output

    - name: Display Disk Size Information
      ansible.builtin.shell:
        cmd: |
          {% if 'linux' in ansible_os_family|lower %}
          df -h
          {% elif 'win' in ansible_os_family|lower %}
          Get-CimInstance Win32_LogicalDisk | Select-Object DeviceID, Size, FreeSpace | ConvertTo-Json
          {% else %}
          echo "Unsupported OS"
          {% endif %}
      register: disk_output

    - name: Creates output directory
      ansible.builtin.file:
        path: "/etc/ansible/output"
        state: directory
      delegate_to: localhost
      when: "'linux' in ansible_os_family|lower"

    - name: Creates output directory
      ansible.windows.win_shell:
        cmd: New-Item -Path C:\ansible\output -ItemType Directory -Force
      ignore_errors: yes
      when: "'win' in ansible_os_family|lower"

    - name: Save output to a single file for all hosts
      ansible.builtin.copy:
        content: |
          {
            {% for host in groups['all'] %}
            "{{ host }}": {
              "Host": "{{ hostvars[host]['ansible_hostname'] }}",
              "CPU Usage (%)": {{ cpu_output.stdout | float | round(2) }},
              "Memory Information": {{ memory_output.stdout | to_nice_json }},
              "Disk Size Information": {{ disk_output.stdout | to_nice_json }}
            }{% if not loop.last %},{% endif %}
            {% endfor %}
          }
        dest: "/etc/ansible/output/out-get_sysspec_all_hosts.json"
      delegate_to: localhost
      when: "'linux' in ansible_os_family|lower"
